export function renderHelpText() {
  return `KualityForge

Usage:
  kualityforge init --artifact-root <path> --run-id <id> [--profile <name>] [--project-root <path>] [--docs-root <path>] [--quality-principles <json>] [--change-goal <text>] [--instruction <path>] [--design-entrypoint <path>] [--diff-base <ref>] [--diff-head <ref|WORKTREE>] [--diff-max-patch-bytes <n>]
  kualityforge run --artifact-root <path> --run-id <id> --review <review.md>... --decision <decision.md> --check <name=status> --verify <verify.md> --verifier-runner-id <id> [--project-root <path>] [--docs-root <path>] [--quality-principles <json>] [--change-goal <text>]
  kualityforge review --project <path> --agent <name>... [--agent <name=path.md>]... [--report] [--html] [--lang <zh|en>] [--out <dir>]
  kualityforge write-review --artifact-root <path> --input <review.md>
  kualityforge synthesize --artifact-root <path>
  kualityforge decide --artifact-root <path> --input <decision.md>
  kualityforge record-check --artifact-root <path> --name <name> --status <status>
  kualityforge verify --artifact-root <path> --runner-id <id> --status <status> --input <verify.md>
  kualityforge gate --manifest <path>
  kualityforge gate --artifact-root <path> [--policy <path>]
  kualityforge report --artifact-root <path> [--out <dir>|--report-out <dir>] [--html]
  kualityforge report --input <manifest.json> [--html] [--lang <zh|en>] [--output <file>]
  kualityforge kswarm-preview [--project-id <id>] [--run-id <id>] [--artifact-root <path>] [--reviewer <name>...] [--advisory-reviewer <name>...] [--quorum-min <n>] [--kswarm-url <url>] [--project-root <path>] [--docs-root <path>] [--quality-principles <json>] [--change-goal <text>] [--target <path>] [--requested-by <id>]
  kualityforge kswarm-run --offline --preview <preview.json> --plan <runtime-plan.json> --review <runner-id=review.md>... [--advisory-reviewer <runner-id>...] [--quorum-min <n>] --decision <decision.md> --check <name=status> [--verify <verify.md> --verifier-runner-id <id>]
  kualityforge kswarm-run --mode brokered [--kswarm-url <url>] [--preview <preview.json> --plan <runtime-plan.json>] [--reviewer <name>...] [--advisory-reviewer <name>...] [--quorum-min <n>] [--decision <decision.md>] [--check <name=status>] [--verify <verify.md> --verifier-runner-id <id>] [--report-out <dir>] [--no-report] [--no-html] [--lang <zh|en>] [--poll-interval-ms <ms>] [--timeout-ms <ms>]
  kualityforge list-agents [--kswarm-url <url>] [--json]
  kualityforge eval [--corpus <dir>] [--report <path>]

Reports:
  report output directory precedence: --report-out flag, then KUALITYFORGE_REPORT_OUT_DIR env var, then the built-in default.

KSwarm URL:
  --kswarm-url can be omitted when KSWARM_URL env var is set. Affects: kswarm-run --mode brokered, kswarm-preview (auto-discover), list-agents.

Smart defaults (kswarm-preview and kswarm-run --mode brokered):
  --project-id    defaults to the directory name of --project-root (or cwd if omitted).
  --run-id        defaults to <project-id>-<YYYYMMDD>.
  --artifact-root defaults to $KUALITYFORGE_ARTIFACT_ROOT_BASE/<project-id>/quality/<run-id> if env var set,
                  otherwise ./kualityforge-runs/<run-id> relative to cwd.
  --reviewer      if omitted and KSWARM_URL/--kswarm-url is set, all online non-xiaok agents are auto-selected.
  --preview/--plan omit both for inline mode: kswarm-run builds them from the same args as kswarm-preview.
  --decision      optional in brokered mode; omit if no human-decision artifact is available.
  --report-out    defaults to the parent of artifact-root (the quality/<run-id>/../ dir).
  HTML report is generated by default; use --no-report or --no-html to suppress.
  Reviewer names accept short forms: codex, claude, qoder, xiaok (KSwarm routes to the active agent).

Quorum review:
  --reviewer marks a required reviewer; --advisory-reviewer marks an advisory (non-blocking) reviewer.
  --advisory-reviewer cannot downgrade a runner already declared as --reviewer (required); doing so is rejected.
  --quorum-min <n> enables quorum mode: at least n of the quorum members (required + advisory) must succeed.
  Required reviewers are never exempted: a missing or failed required reviewer always blocks the gate,
  while advisory absence only records warnings.
`;
}
