export const DEFAULT_LANG = "zh";

const LABELS = {
  zh: {
    title: "KualityForge 评审报告",
    field: "字段", value: "值",
    profile: "Profile", gateStatus: "Gate 状态",
    gateReasons: "Gate 原因", gateWarnings: "Gate 警告",
    changeset: "变更集",
    noChangesetFrozen: "未冻结变更集",
    noChangesetReason: (r) => `未冻结变更集（${r}）`,
    base: "Base", head: "Head", filesChanged: "变更文件数",
    patchTruncated: "Patch 截断",
    patchTruncatedYes: "是（部分 hunk 超出范围）", patchTruncatedNo: "否",
    status: "状态", path: "路径",
    findingsTitle: "发现 (F#)",
    noFindings: "未发现问题。",
    fNum: "#", fTitle: "标题", fSeverity: "严重程度", fStatus: "状态", fReviewers: "评审员", fCount: "数量", fId: "Id",
    fDescription: "详情", fSuggestion: "建议",
    consensusTitle: "共识发现 (G#)",
    noConsensus: "无共识发现（>=2 名评审员）。",
    scoresTitle: "评审员评分",
    noScores: "未计算评审员评分。",
    sReviewer: "评审员", sScore: "分数", sFindings: "Findings 数", sConsensus: "共识率", sRole: "角色",
    ranking: "排名",
    principlesTitle: "归纳质量原则候选 (P#, 咨询性)",
    noPrinciples: "未归纳候选原则。",
    pNum: "#", pPriority: "优先级", pStatement: "描述", pId: "Id",
    decisionsTitle: "决策与验证",
    gateDecision: "Gate 决策",
    totalFindings: (total, consensus) => `${total} 个，${consensus} 个达成共识`,
    inducedCount: (n) => `${n} 个（咨询性；是否纳入由人工决定）`,
    findingsLabel: "总发现数", inducedLabel: "归纳候选原则",
    reviewType: "评审模式", reviewTypeChangeset: "变更集评审", reviewTypeFullProject: "全量项目评审",
    projectOverviewTitle: "项目概览",
    projectName: "项目名称", projectVersion: "版本", reviewScope: "评审范围",
    techStack: "技术栈", codeScale: "代码规模", reviewerCountLabel: "评审员数",
    reviewerDetailsTitle: "评审员详细分析 (R#)",
    rSubDim: "子维度", rScore: "评分", rFinding: "关键发现",
    rTopIssues: "Top 问题", rSeverity: "严重度", rIssue: "问题", rLocation: "位置",
    rImprovements: "改进建议", rPriority: "优先级", rSuggestion: "建议", rBenefit: "预期收益",
    riskMatrixTitle: "风险矩阵",
    rskName: "风险", rskProb: "概率", rskImpact: "影响", rskScore: "风险分", rskCategory: "类别", rskFindings: "关联 Finding",
    actionPlanTitle: "行动路线",
    actPriority: "优先级", actAction: "行动", actEffort: "预估投入", actFindings: "关联 Finding",
    overallGradeTitle: "综合评级",
    ogDim: "维度", ogScore: "评分", ogReviewer: "评审员",
    ogGrade: "综合评级", ogReason: "评级理由", ogUpgradePath: "升级路径",
    htmlLang: "zh",
  },
  en: {
    title: "KualityForge Report",
    field: "Field", value: "Value",
    profile: "Profile", gateStatus: "Gate status",
    gateReasons: "Gate reasons", gateWarnings: "Gate warnings",
    changeset: "Changeset",
    noChangesetFrozen: "No changeset was frozen.",
    noChangesetReason: (r) => `No changeset was frozen (${r}).`,
    base: "Base", head: "Head", filesChanged: "Files changed",
    patchTruncated: "Patch truncated",
    patchTruncatedYes: "yes (some hunks out of scope)", patchTruncatedNo: "no",
    status: "Status", path: "Path",
    findingsTitle: "Findings (F#)",
    noFindings: "No findings were reported.",
    fNum: "#", fTitle: "Title", fSeverity: "Severity", fStatus: "Status", fReviewers: "Reviewers", fCount: "Count", fId: "Id",
    fDescription: "Description", fSuggestion: "Suggestion",
    consensusTitle: "Consensus Findings (G#)",
    noConsensus: "No findings reached consensus (>= 2 reviewers).",
    scoresTitle: "Reviewer Scores",
    noScores: "No reviewer scores were computed.",
    sReviewer: "Reviewer", sScore: "Score", sFindings: "Findings", sConsensus: "Consensus", sRole: "Role",
    ranking: "Ranking",
    principlesTitle: "Induced Principle Candidates (P#, advisory)",
    noPrinciples: "No candidate principles were induced.",
    pNum: "#", pPriority: "Priority", pStatement: "Statement", pId: "Id",
    decisionsTitle: "Decisions & Verification",
    gateDecision: "Gate decision",
    totalFindings: (total, consensus) => `${total} total, ${consensus} at consensus`,
    inducedCount: (n) => `${n} (advisory; human decides adoption)`,
    findingsLabel: "Findings", inducedLabel: "Induced candidates",
    reviewType: "Review type", reviewTypeChangeset: "Changeset review", reviewTypeFullProject: "Full-project review",
    projectOverviewTitle: "Project Overview",
    projectName: "Project", projectVersion: "Version", reviewScope: "Scope",
    techStack: "Tech stack", codeScale: "Code scale", reviewerCountLabel: "Reviewers",
    reviewerDetailsTitle: "Reviewer Details (R#)",
    rSubDim: "Sub-dimension", rScore: "Score", rFinding: "Key findings",
    rTopIssues: "Top issues", rSeverity: "Severity", rIssue: "Issue", rLocation: "Location",
    rImprovements: "Improvements", rPriority: "Priority", rSuggestion: "Suggestion", rBenefit: "Expected benefit",
    riskMatrixTitle: "Risk Matrix",
    rskName: "Risk", rskProb: "Prob", rskImpact: "Impact", rskScore: "Risk score", rskCategory: "Category", rskFindings: "Related findings",
    actionPlanTitle: "Action Plan",
    actPriority: "Priority", actAction: "Action", actEffort: "Effort", actFindings: "Related findings",
    overallGradeTitle: "Overall Grade",
    ogDim: "Dimension", ogScore: "Score", ogReviewer: "Reviewer",
    ogGrade: "Grade", ogReason: "Rationale", ogUpgradePath: "Upgrade path",
    htmlLang: "en",
  }
};

export function getLabels(lang) {
  return LABELS[lang] || LABELS[DEFAULT_LANG];
}
